name: flutter_hook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.1
  build_runner: ^2.3.3
  riverpod_lint: ^1.3.1
  custom_lint: ^0.3.4

flutter:
  uses-material-design: true
